apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: bike-app-backend
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/bikes-app
          image: wojpon/bike-app-backend:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          resources: {}
