apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: bike-app-frontend
          image: wojpon/bike-app-frontend:1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_API_URL
              value: '/api/v1'
          ports:
            - containerPort: 80
          resources: {}
